name: Deploy Next.js application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t kevindev71/poc-nextjs-middleware-ec2 .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push kevindev71/poc-nextjs-middleware-ec2:latest
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull image from docker hub
        run: docker pull kevindev71/poc-nextjs-middleware-ec2:latest
      - name: Delete old container
        run: docker rm -f poc-nextjs-middleware-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name poc-nextjs-middleware-container kevindev71/poc-nextjs-middleware-ec2
